# Generated by Django 3.2.2 on 2022-01-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0003_alter_text_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_public',
        ),
        migrations.AddField(
            model_name='project',
            name='access',
            field=models.CharField(choices=[('pr', 'Private'), ('pu', 'Public')], default='pu', max_length=2),
        ),
    ]
