# Generated by Django 3.2.2 on 2022-01-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0004_auto_20220129_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='access',
            field=models.CharField(choices=[('pu', 'Public'), ('pr', 'Private')], default='pu', max_length=2),
        ),
    ]
